// Generate QGIS project file (.qlr bundle) for all Phase 1-3 layers
// Run: npx tsx scripts/generate-qgis-project.ts
// Output: export/place-time-five-towns.qlr

import { writeFileSync, existsSync, mkdirSync, readFileSync } from 'fs';
import { join, relative, dirname } from 'path';
import { fileURLToPath } from 'url';
import { writeQlrFile, generateQlrLayer } from '../src/core/qgis.js';
import type { GeoFeature } from '../src/core/types.js';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const ROOT = join(__dirname, '..');
const EXPORT_DIR = join(ROOT, 'export');
const DATA_DIR = join(ROOT, 'data');

if (!existsSync(EXPORT_DIR)) mkdirSync(EXPORT_DIR, { recursive: true });

interface LayerSpec {
  id: string;
  name: string;
  description: string;
  source: string;
  dataPath: string; // relative to project root
  style: { fillColor: string; fillOpacity: number; strokeColor: string; strokeWidth: number };
  validFrom: number | null;
  validTo: number | null;
}

const LAYERS: LayerSpec[] = [
  // Phase 3 — Political (on top, high priority)
  {
    id: 'political:ward-wakefield',
    name: 'Wakefield Wards (2023)',
    description: '21 electoral wards in Wakefield MDC',
    source: 'ONS Open Geography Portal (OGL)',
    dataPath: 'data/boundaries/wards-wakefield.geojson',
    style: { fillColor: '160,120,200,255', fillOpacity: 0.08, strokeColor: '80,60,120,255', strokeWidth: 0.6 },
    validFrom: null, validTo: null,
  },
  {
    id: 'political:westminster-constituency',
    name: 'Westminster Constituencies (Five Towns)',
    description: '12 constituencies intersecting Five Towns area (2022 boundaries)',
    source: 'ONS Open Geography Portal (OGL)',
    dataPath: 'data/boundaries/constituencies-five-towns.geojson',
    style: { fillColor: '180,100,180,255', fillOpacity: 0.12, strokeColor: '100,50,120,255', strokeWidth: 1.2 },
    validFrom: null, validTo: null,
  },
  // Phase 3 — Admin
  {
    id: 'admin:lad-wakefield',
    name: 'Wakefield Metropolitan District',
    description: 'Wakefield MDC administrative boundary',
    source: 'ONS Open Geography Portal (OGL)',
    dataPath: 'data/boundaries/wakefield-mdc.geojson',
    style: { fillColor: '80,160,80,255', fillOpacity: 0.06, strokeColor: '40,100,40,255', strokeWidth: 2.0 },
    validFrom: null, validTo: null,
  },
  {
    id: 'admin:county-west-yorkshire',
    name: 'West Yorkshire',
    description: 'West Yorkshire boundary',
    source: 'ONS Open Geography Portal (OGL)',
    dataPath: 'data/boundaries/west-yorkshire.geojson',
    style: { fillColor: '60,120,60,255', fillOpacity: 0.04, strokeColor: '30,80,30,255', strokeWidth: 2.5 },
    validFrom: null, validTo: null,
  },
  // Phase 2 — Historical
  {
    id: 'historical:cliopatria-boundary',
    name: 'Cliopatria UK Polities',
    description: 'UK temporal political boundaries 400–2024 CE',
    source: 'Cliopatria / Seshat Global History Databank (CC-BY-NC)',
    dataPath: 'data/historical/cliopatria-uk.geojson',
    style: { fillColor: '120,80,160,255', fillOpacity: 0.15, strokeColor: '60,40,100,255', strokeWidth: 0.5 },
    validFrom: null, validTo: null,
  },
  {
    id: 'historical:osm-settlement',
    name: 'Yorkshire Settlements (OSM)',
    description: '420 named settlements in Yorkshire bounding box',
    source: 'OpenStreetMap via Overpass API (ODbL)',
    dataPath: 'data/historical/yorkshire-settlements-osm.geojson',
    style: { fillColor: '180,160,80,255', fillOpacity: 0.7, strokeColor: '100,90,40,255', strokeWidth: 0.8 },
    validFrom: null, validTo: null,
  },
  {
    id: 'historical:domesday-settlement',
    name: 'Domesday Settlements 1086',
    description: '10 Five Towns Domesday places (Palmer/Hull dataset)',
    source: 'Palmer/Hull Domesday dataset (ODbL)',
    dataPath: 'data/historical/domesday-five-towns.geojson',
    style: { fillColor: '220,180,40,255', fillOpacity: 1.0, strokeColor: '140,110,20,255', strokeWidth: 2.0 },
    validFrom: 1086, validTo: 1086,
  },
  // Phase 1 — Hex grids
  {
    id: 'hex:five-towns-res8',
    name: 'Five Towns H3 Grid (Res 8)',
    description: 'H3 resolution 8 hex grid (~8.7km edge) for Five Towns area',
    source: 'Generated by place-time/scripts/phase1-grid-calibration.ts',
    dataPath: 'data/five-towns/five-towns-grid-res8.geojson',
    style: { fillColor: '200,220,240,255', fillOpacity: 0.0, strokeColor: '100,150,200,255', strokeWidth: 0.4 },
    validFrom: null, validTo: null,
  },
  {
    id: 'hex:five-towns-res7',
    name: 'Five Towns H3 Grid (Res 7)',
    description: 'H3 resolution 7 hex grid (~1.2km edge) for regional context',
    source: 'Generated by place-time/scripts/phase1-grid-calibration.ts',
    dataPath: 'data/five-towns/five-towns-grid-res7.geojson',
    style: { fillColor: '180,210,240,255', fillOpacity: 0.0, strokeColor: '80,130,180,255', strokeWidth: 0.7 },
    validFrom: null, validTo: null,
  },
  // Phase 1 — Geology (bottom layers)
  {
    id: 'geology:province',
    name: 'Geological Provinces',
    description: 'Global geological provinces (placeholder — replace with BGS OGC API data)',
    source: 'BGS placeholder / Zenodo GPlates 2.5 GeoData',
    dataPath: 'data/geology/geological_provinces.geojson',
    style: { fillColor: '160,120,80,255', fillOpacity: 0.25, strokeColor: '80,60,40,255', strokeWidth: 0.5 },
    validFrom: null, validTo: null,
  },
  {
    id: 'geology:tectonic-plate',
    name: 'Tectonic Plates',
    description: '54 world tectonic plate boundaries (PB2002)',
    source: 'fraxen/tectonicplates (ODC-BY)',
    dataPath: 'data/geology/tectonic_plates.geojson',
    style: { fillColor: '180,100,80,255', fillOpacity: 0.1, strokeColor: '100,50,40,255', strokeWidth: 0.8 },
    validFrom: null, validTo: null,
  },
];

function loadFeatures(relPath: string): GeoFeature[] {
  const absPath = join(ROOT, relPath);
  if (!existsSync(absPath)) {
    console.warn(`  MISSING: ${relPath}`);
    return [];
  }
  const fc = JSON.parse(readFileSync(absPath, 'utf-8')) as GeoJSON.FeatureCollection;
  return (fc.features ?? []) as GeoFeature[];
}

export function generateQgisProject(): void {
  console.log('\n=== Generating QGIS Project ===\n');

  const outputPath = join(EXPORT_DIR, 'place-time-five-towns.qlr');
  const outputDir = dirname(outputPath);

  const qlrLines: string[] = [];
  const layerTreeLines: string[] = [];
  const legendLines: string[] = [];
  let loaded = 0;

  for (const spec of LAYERS) {
    const features = loadFeatures(spec.dataPath);
    if (features.length === 0) continue;

    const layer = {
      id: spec.id,
      name: spec.name,
      description: spec.description,
      source: spec.source,
      validFrom: spec.validFrom,
      validTo: spec.validTo,
      features,
      style: spec.style,
    };

    const dataAbsPath = join(ROOT, spec.dataPath);

    // Individual QLR alongside the data file — path relative to that QLR's own directory
    const individualQlrPath = join(ROOT, spec.dataPath.replace('.geojson', '.qlr'));
    const pathFromIndividualQlr = relative(dirname(individualQlrPath), dataAbsPath).replace(/\\/g, '/');
    try {
      writeQlrFile({ layer, dataPath: pathFromIndividualQlr }, individualQlrPath);
    } catch {
      // Some layers may fail QLR if geometry type is not Polygon
    }

    // Combined project QLR — path relative to export/ directory
    const pathFromCombinedQlr = relative(outputDir, dataAbsPath).replace(/\\/g, '/');
    try {
      const qlrXml = generateQlrLayer({ layer, dataPath: pathFromCombinedQlr });
      const match = qlrXml.match(/<maplayer[\s\S]*?<\/maplayer>/);
      if (match) {
        qlrLines.push(match[0]);
        layerTreeLines.push(`    <layer-tree-layer id="${spec.id}" name="${spec.name}" source="${pathFromCombinedQlr}" providerKey="ogr"/>`);
        legendLines.push(`    <legendlayer open="true" checked="Qt::Checked" name="${spec.name}"><filegroup><legendlayerfile isInOverview="0" layerid="${spec.id}"/></filegroup></legendlayer>`);
        loaded++;
        console.log(`  ✓ ${spec.name} (${features.length} features)`);
      }
    } catch {
      // skip layers that fail
    }
  }

  // Write combined QGIS project XML
  const projectXml = `<?xml version="1.0" encoding="UTF-8"?>
<qgis project version="3.38">
  <layer-tree-group expanded="1" checked="Qt::PartiallyChecked" name="">
${layerTreeLines.join('\n')}
  </layer-tree-group>
  <legend update="0">
${legendLines.join('\n')}
  </legend>
  <maplayers>
${qlrLines.join('\n')}
  </maplayers>
</qgis>`;

  writeFileSync(outputPath, projectXml, 'utf-8');

  console.log(`\nProject written: ${outputPath}`);
  console.log(`Layers included: ${loaded}/${LAYERS.length}`);
  console.log('\nTo open in QGIS: Layer > Add from Layer Definition File > select the .qlr');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  generateQgisProject();
}
